### ISSUE TITLE
deprecated_stop() should say defunct instead of deprecated

### ISSUE THREAD

**Issue by hadley** [r-lib/lifecycle#28]
```
> lifecycle::deprecate_stop("1.0.0", "foo()", "foo(bar = )")
Error: `foo()` is deprecated as of <NA> 1.0.0.
Please use the `bar` argument instead.
```

**Comment by lionel-** [comment]
This isn't a straightforward change because it requires providing a full deprecation cycle as package versions. Or at least change the meaning of the version in `deprecate_stop()` so that it represents the version at which the function stopped working instead of the version at which it was deprecated.

The UI was made to minimise intervention when bumping the lifecycle, so that all `_warn` can be bumped to `_stop` by bulk search&replace for instance.

**Comment by hadley** [comment]
Maybe “foo() was deprecated in PKG VERSION and is now defunct”?

**Comment by lionel-** [comment]
why didn't I think of that :)
