### ISSUE TITLE
Sentinel for deprecated arguments?

### ISSUE THREAD

**Issue by lionel-** [r-lib/lifecycle#4]
E.g. `foo = deprecated()`

**Comment by lionel-** [comment]
@hadley How about having `deprecated()` just return `missing_arg()`, then we could test for it quite naturally:

```r
foo <- function(bar, baz = deprecated()) {
  if (!is_missing(baz)) {
    deprecate_warn("1.0.0", "foo(baz = )")
  }

  ...
}
```

**Comment by hadley** [comment]
Oh interesting.

**Comment by hadley** [comment]
The main downside of this would be creating a "magical" argument: https://principles.tidyverse.org/def-magical.html.  Seems like the tradeoff might be worth it here, since `deprecated()` is just a sentinel, the meaning should be obvious here, and there's no reason for the user to call `deprecated()`.
